name: cidadania_ativa
description: Aplicativo Cidadania Ativa
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Ajustado para compatibilidade padrão com Flutter 3.x

dependencies:
  flutter:
    sdk: flutter

  # Dependências alinhadas corretamente com 2 espaços:
  provider: ^6.1.2
  http: ^1.2.2
  file_picker: ^8.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
